USE [BookMe]
GO

/****** Object:  Table [dbo].[Avtor]    Script Date: 04/05/2012 23:09:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Avtor](
	[ID] [int] NOT NULL,
	[Avtor] [nvarchar](500) NULL,
	[Variante] [nvarchar](500) NULL,
 CONSTRAINT [PK_Avtor] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

