USE [BookMe]
GO

/****** Object:  Table [dbo].[Gradivo]    Script Date: 04/05/2012 23:09:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Gradivo](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Vrsta] [nvarchar](200) NULL,
 CONSTRAINT [PK_Gradivo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

