USE [BookMe]
GO

/****** Object:  Table [dbo].[Jezik]    Script Date: 04/05/2012 23:10:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Jezik](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Jezik] [nvarchar](100) NULL,
 CONSTRAINT [PK_Jezik] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

